
# Docker Compose for development Postgres
#
# Usage:
#   Start containers: docker-compose -f docker-compose.dev.yml up -d
#   Stop containers: docker-compose -f docker-compose.dev.yml stop
#   Remove containers: docker-compose -f docker-compose.dev.yml down
#   Restart containers: docker-compose -f docker-compose.dev.yml restart

services:
  postgres-dev:
    image: postgres:15
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: saba
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:


